env:
  browser: true
  es6: true

extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended

settings:
  react: { version: detect }

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module

rules:
  prettier/prettier: ["warn"]
  react/prop-types: ["off"]
  react-hooks/rules-of-hooks: ["warn"]
  react-hooks/exhaustive-deps: 
    - warn
    - additionalHooks: useEffectOnce
  indent: ["error", 2]
  linebreak-style: ["error", "unix"]
  quotes: ["error", "double"]
  semi: ["error", "always"]
